### ISSUE TITLE
Add Instagram to chapter social links

### ISSUE THREAD

**Issue by jcn** [awesomefoundation/awesomebits#313] opened 2018-10-27 17:20 UTC
* Add an attribute to the `Chapter` model called `instagram_url`
* Add the field to the chapter edit page
* If it is set, add an instagram icon (need to create one) to the chapter page

https://www.facebook.com/groups/awesomefound/permalink/2156513644381593/

![43614907_10110276190713250_7299080947121520640_n](https://user-images.githubusercontent.com/2909/47607171-a0506c80-d9ea-11e8-8bbb-1d0404f71e01.jpg)

![screen shot 2018-10-27 at 1 17 48 pm](https://user-images.githubusercontent.com/2909/47607185-d7268280-d9ea-11e8-8ecf-9032c3f01990.png)

**Comment by avicaplan** [comment] 2018-10-27 17:37
Actually a duplicate of https://github.com/awesomefoundation/awesomebits/issues/302. But better. :)

**Comment by jcn** [comment] 2018-10-29 00:51
> Actually a duplicate of #302. But better. :)

Blast, you're right. Closing the other one.

**Closed** 2019-02-16 00:31 UTC
