### ISSUE TITLE
mobile scrolling of projects is broken

### ISSUE THREAD

**Issue by forensicgarlic** [awesomefoundation/awesomebits#282] opened 2017-10-17 21:57 UTC
on desktop, when you go to a chapter page, and move your mouse over the bar with award winners, an arrow pops up allowing you to scroll right, and then right and left on awards that have been given. 

On mobile (or android anyway), without the concept of a mouse, it only pops up when you tap a winner. This means that unless your phone thinks you're trying to zoom in, you are navigated to that winner instead of having the option of scrolling.

**Comment by jcn** [comment] 2017-10-17 22:01
Definitely an issue - hopefully someone will be able to address this soon. 

Closing as it is a duplicate of issue #99.

**Closed by jcn** 2017-10-17 22:01 UTC

**Comment by forensicgarlic** [comment] 2017-10-17 22:05
damn, sorry about that. I looked through issues, but not all of them apparently.

**Comment by jcn** [comment] 2017-10-17 22:05
No worries - it's a _very_ old issue.
